language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"
services:
  - rabbitmq
# command to run unit tests
script: python -m unittest discover test/unit
# command to run acceptance tests
script: python -m unittest discover test/acceptance
